
export const TRY_FETCH_ARTICLES = 'TRY_FETCH_ARTICLES';
export const FETCH_ARTICLES = 'FETCH_ARTICLES';

export const TRY_FETCH_ARTICLE = 'TRY_FETCH_ARTICLE';
export const FETCH_ARTICLE = 'FETCH_ARTICLE';

export const TRY_FETCH_MY_ARTICLES = 'TRY_FETCH_MY_ARTICLES';
export const FETCH_MY_ARTICLES = 'FETCH_MY_ARTICLES';

export const TRY_CREATE_ARTICLE = 'TRY_CREATE_ARTICLE';

export const TRY_FETCH_ARTICLE_TO_EDIT = 'TRY_FETCH_ARTICLE_TO_EDIT';
export const FETCH_ARTICLE_TO_EDIT = 'FETCH_ARTICLE_TO_EDIT';

export const TRY_EDIT_ARTICLE = 'TRY_EDIT_ARTICLE';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';

export const RESET_FORM = 'RESET_FORM';